# Loding Libraries

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Uploading dataset

In [2]:
df=pd.read_csv('telefon turini aniqlash2.csv')

# Introducing with Data

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001 entries, 0 to 2000
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   battereya_hajmi                2001 non-null   int64
 1   blutus                         2001 non-null   int64
 2   protsessor_tezligi             2001 non-null   float64
 3   ikkita simkartalik             2001 non-null   int64
 4   Oldi_kamera                    2001 non-null   int64
 5   4G                             2001 non-null   int64
 6   Ichki_xotira                   2001 non-null   int64
 7   tel_ingichgaligi               1998 non-null   float64
 8   Rangi                          2001 non-null   object
 9   Vazni                          2001 non-null   int64
 10  Protsessor yadrolari soni      2000 non-null   float64
 11  Asosiy kamera                  1999 non-null   float64
 12  Qurilma xajmi(pix)             1999 non-null   float64
 13  Qurilma ekran kengligi(pix)    1998 non-null   float64
 14  ram                            2001 non-null   int64
 15  Qurilma xajmi(cm)              2000 non-null   float64
 16  Qurilma ekran kengligi(cm)     2000 non-null   float64
 17  Bir_quvvatlashdagi gaplashish  2001 non-null   int64
 18  3g                             2001 non-null   int64
 19  Qurilma xajmi(pix).1           1999 non-null   float64
 20  sensorli                       2001 non-null   int64
 21  wifi                           2001 non-null   int64
 22  telefon_turi                   2001 non-null   int64
dtypes: float64(9), int64(13), object(1)
memory usage: 359.7+ KB

In [4]:
df.head()

,battereya_hajmi,blutus,protsessor_tezligi,ikkita simkartalik,Oldi_kamera,4G,Ichki_xotira,tel_ingichgaligi,Rangi,Vazni,...,Qurilma ekran kengligi(pix),ram,Qurilma xajmi(cm),Qurilma ekran kengligi(cm),Bir_quvvatlashdagi gaplashish,3g,Qurilma xajmi(pix).1,sensorli,wifi,telefon_turi
0,842,0,2.2,0,1,0,7,0.6,Qizil,188,...,756.0,2549,9.0,7.0,19,0,20.0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,Yashil,136,...,1988.0,2631,17.0,3.0,7,1,905.0,1,0,2
2,563,1,0.5,1,2,1,41,0.9,Sariq,145,...,1716.0,2603,11.0,2.0,9,1,1263.0,1,0,2
3,615,1,2.5,0,0,0,10,0.8,Jigarrang,131,...,1786.0,2769,16.0,8.0,11,1,1216.0,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,Oq,141,...,1212.0,1411,8.0,2.0,15,1,1208.0,1,0,1

In [5]:
df.describe()

,battereya_hajmi,blutus,protsessor_tezligi,ikkita simkartalik,Oldi_kamera,4G,Ichki_xotira,tel_ingichgaligi,Vazni,Protsessor yadrolari soni,...,Qurilma ekran kengligi(pix),ram,Qurilma xajmi(cm),Qurilma ekran kengligi(cm),Bir_quvvatlashdagi gaplashish,3g,Qurilma xajmi(pix).1,sensorli,wifi,telefon_turi
count,2001.000000,2001.000000,2001.000000,2001.000000,2001.000000,2001.000000,2001.000000,1998.000000,2001.000000,2000.000000,...,1998.000000,2001.000000,2000.000000,2000.000000,2001.000000,2001.000000,1999.000000,2001.000000,2001.000000,2001.000000
mean,1238.876062,0.494753,1.521739,0.509745,4.307346,0.521239,32.042479,0.501952,140.272364,4.519500,...,1251.277277,2123.501249,12.310000,5.767000,11.007996,0.761619,645.349675,0.503248,0.507246,1.499250
std,439.599414,0.500097,0.816120,0.500030,4.341427,0.499674,18.142070,0.288524,35.406232,2.287627,...,432.133097,1084.928094,4.213404,4.356398,5.464242,0.426200,443.770025,0.500114,0.500072,1.118537
min,501.000000,0.000000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,...,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,852.000000,0.000000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.000000,...,875.250000,1206.000000,9.000000,2.000000,6.000000,1.000000,283.500000,0.000000,0.000000,0.000000
50%,1227.000000,0.000000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.000000,...,1247.000000,2146.000000,12.000000,5.000000,11.000000,1.000000,564.000000,1.000000,1.000000,1.000000
75%,1616.000000,1.000000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.000000,...,1632.750000,3064.000000,16.000000,9.000000,16.000000,1.000000,947.500000,1.000000,1.000000,2.000000
max,1998.000000,1.000000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.000000,...,1998.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1960.000000,1.000000,1.000000,3.000000

# Data Preprocessing with Class

In [6]:
df.isnull().sum()

battereya_hajmi                  0
blutus                           0
protsessor_tezligi               0
ikkita simkartalik               0
Oldi_kamera                      0
4G                               0
Ichki_xotira                     0
tel_ingichgaligi                 3
Rangi                            0
Vazni                            0
Protsessor yadrolari soni        1
Asosiy kamera                    2
Qurilma xajmi(pix)               2
Qurilma ekran kengligi(pix)      3
ram                              0
Qurilma xajmi(cm)                1
Qurilma ekran kengligi(cm)       1
Bir_quvvatlashdagi gaplashish    0
3g                               0
Qurilma xajmi(pix).1             2
sensorli                         0
wifi                             0
telefon_turi                     0
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
class DataPreprocessing:
    def __init__(self,df):
        self.df=df
    def tozala(self):
        for col in self.df.columns:
            if self.df[col].isnull().any():
                if self.df[col].dtype=='object':
                    self.df[col].fillna(self.df[col].mode()[0],inplace=True)                
                else:
                    self.df[col].fillna(self.df[col].mean(),inplace=True)
        return self
    def encodla(self):
        encoder=LabelEncoder()
        for col in self.df.columns:
            if self.df[col].dtype=='object':
                if self.df[col].nunique()<=5:
                    dummies=pd.get_dummies(self.df[col],prefix=col,dtype=int)
                    self.df=pd.concat([self.df.drop(columns=col),dummies],axis=1)
                else:
                    self.df[col]=encoder.fit_transform(self.df[col])
        return self
    def scale_qil(self):
        scaler=MinMaxScaler()
        for col in self.df.columns:
            num_col=self.df.select_dtypes(include=['int64','float64']).columns.drop('telefon_turi')
            self.df[num_col]=scaler.fit_transform(self.df[num_col])
        return self

In [13]:
dp=DataPreprocessing(df)
dp.tozala().encodla().scale_qil()
preprocessed_data=dp.df

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001 entries, 0 to 2000
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   battereya_hajmi                2001 non-null   float64
 1   blutus                         2001 non-null   float64
 2   protsessor_tezligi             2001 non-null   float64
 3   ikkita simkartalik             2001 non-null   float64
 4   Oldi_kamera                    2001 non-null   float64
 5   4G                             2001 non-null   float64
 6   Ichki_xotira                   2001 non-null   float64
 7   tel_ingichgaligi               2001 non-null   float64
 8   Rangi                          2001 non-null   float64
 9   Vazni                          2001 non-null   float64
 10  Protsessor yadrolari soni      2001 non-null   float64
 11  Asosiy kamera                  2001 non-null   float64
 12  Qurilma xajmi(pix)             2001 non-null   float64
 13  Qurilma ekran kengligi(pix)    2001 non-null   float64
 14  ram                            2001 non-null   float64
 15  Qurilma xajmi(cm)              2001 non-null   float64
 16  Qurilma ekran kengligi(cm)     2001 non-null   float64
 17  Bir_quvvatlashdagi gaplashish  2001 non-null   float64
 18  3g                             2001 non-null   float64
 19  Qurilma xajmi(pix).1           2001 non-null   float64
 20  sensorli                       2001 non-null   float64
 21  wifi                           2001 non-null   float64
 22  telefon_turi                   2001 non-null   int64
dtypes: float64(22), int64(1)
memory usage: 359.7 KB

In [15]:
df.head()

,battereya_hajmi,blutus,protsessor_tezligi,ikkita simkartalik,Oldi_kamera,4G,Ichki_xotira,tel_ingichgaligi,Rangi,Vazni,...,Qurilma ekran kengligi(pix),ram,Qurilma xajmi(cm),Qurilma ekran kengligi(cm),Bir_quvvatlashdagi gaplashish,3g,Qurilma xajmi(pix).1,sensorli,wifi,telefon_turi
0,0.227789,0.0,0.68,0.0,0.052632,0.0,0.080645,0.555556,0.4,0.900000,...,0.170895,0.612774,0.285714,0.388889,0.944444,0.0,0.010204,0.0,1.0,1
1,0.347361,1.0,0.00,1.0,0.000000,1.0,0.822581,0.666667,1.0,0.466667,...,0.993324,0.634687,0.857143,0.166667,0.277778,1.0,0.461735,1.0,0.0,2
2,0.041416,1.0,0.00,1.0,0.105263,1.0,0.629032,0.888889,0.8,0.541667,...,0.811749,0.627205,0.428571,0.111111,0.388889,1.0,0.644388,1.0,0.0,2
3,0.076152,1.0,0.80,0.0,0.000000,0.0,0.129032,0.777778,0.0,0.425000,...,0.858478,0.671566,0.785714,0.444444,0.500000,1.0,0.620408,0.0,0.0,2
4,0.881764,1.0,0.28,0.0,0.684211,1.0,0.677419,0.555556,0.2,0.508333,...,0.475300,0.308658,0.214286,0.111111,0.722222,1.0,0.616327,1.0,0.0,1

# Feature Transformation

In [16]:
df=preprocessed_data

In [18]:
# First of All we should determine numerical features
num_col=df.select_dtypes(include=['float64','int64'])

In [19]:
num_col

,battereya_hajmi,blutus,protsessor_tezligi,ikkita simkartalik,Oldi_kamera,4G,Ichki_xotira,tel_ingichgaligi,Rangi,Vazni,...,Qurilma ekran kengligi(pix),ram,Qurilma xajmi(cm),Qurilma ekran kengligi(cm),Bir_quvvatlashdagi gaplashish,3g,Qurilma xajmi(pix).1,sensorli,wifi,telefon_turi
0,0.227789,0.0,0.68,0.0,0.052632,0.0,0.080645,0.555556,0.4,0.900000,...,0.170895,0.612774,0.285714,0.388889,0.944444,0.0,0.010204,0.0,1.0,1
1,0.347361,1.0,0.00,1.0,0.000000,1.0,0.822581,0.666667,1.0,0.466667,...,0.993324,0.634687,0.857143,0.166667,0.277778,1.0,0.461735,1.0,0.0,2
2,0.041416,1.0,0.00,1.0,0.105263,1.0,0.629032,0.888889,0.8,0.541667,...,0.811749,0.627205,0.428571,0.111111,0.388889,1.0,0.644388,1.0,0.0,2
3,0.076152,1.0,0.80,0.0,0.000000,0.0,0.129032,0.777778,0.0,0.425000,...,0.858478,0.671566,0.785714,0.444444,0.500000,1.0,0.620408,0.0,0.0,2
4,0.881764,1.0,0.28,0.0,0.684211,1.0,0.677419,0.555556,0.2,0.508333,...,0.475300,0.308658,0.214286,0.111111,0.722222,1.0,0.616327,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,0.195725,1.0,0.00,1.0,0.000000,1.0,0.000000,0.777778,0.6,0.216667,...,0.927904,0.110102,0.571429,0.222222,0.944444,1.0,0.623469,1.0,0.0,0
1997,0.977956,1.0,0.84,1.0,0.000000,0.0,0.596774,0.111111,0.6,0.891667,...,0.977971,0.474613,0.428571,0.555556,0.777778,1.0,0.466837,1.0,1.0,2
1998,0.941884,0.0,0.16,1.0,0.052632,1.0,0.548387,0.666667,0.6,0.233333,...,0.755674,0.748530,0.285714,0.055556,0.166667,1.0,0.442857,1.0,0.0,3
1999,0.675351,0.0,0.16,0.0,0.210526,1.0,0.709677,0.000000,0.6,0.541667,...,0.113485,0.163816,0.928571,0.555556,0.944444,1.0,0.171429,1.0,1.0,0
2000,0.006012,1.0,0.60,1.0,0.263158,1.0,0.693548,0.888889,0.6,0.733333,...,0.169559,0.978888,1.000000,0.222222,0.000000,1.0,0.246429,1.0,1.0,3

In [28]:
#2 we should find the degrees of skewness
num_col.skew()                   # All in All many more degrees of skewness  is related to  [0:0.5] numbers .it means there is no need to log transormation

battereya_hajmi                  0.031558
blutus                           0.021006
protsessor_tezligi               0.178815
ikkita simkartalik              -0.039017
Oldi_kamera                      1.020313
4G                              -0.085098
Ichki_xotira                     0.058517
tel_ingichgaligi                 0.087999
Rangi                            1.738971
Vazni                            0.005722
Protsessor yadrolari soni        0.004801
Asosiy kamera                    0.019397
Qurilma xajmi(pix)               0.665905
Qurilma ekran kengligi(pix)      0.016144
ram                              0.007459
Qurilma xajmi(cm)               -0.100813
Qurilma ekran kengligi(cm)       0.633945
Bir_quvvatlashdagi gaplashish    0.010490
3g                              -1.228912
Qurilma xajmi(pix).1             0.665905
sensorli                        -0.013004
wifi                            -0.029010
telefon_turi                     0.000806
dtype: float64

In [29]:
skewness=num_col.skew()

In [30]:
#3 Separate the values that should go through log transformation by filtering.
log_transformation=skewness[(skewness>=0.5)].index.tolist()

In [ ]:
log_transformation  # demak shu 4 columndagi featurelar Log transformation qilishga

['Oldi_kamera',
 'Rangi',
 'Qurilma xajmi(pix)',
 'Qurilma ekran kengligi(cm)',
 'Qurilma xajmi(pix).1']

In [32]:
#4 apllying Log transformation
for col in log_transformation:
    df[col+'_log']=np.log1p(df[col])

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001 entries, 0 to 2000
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   battereya_hajmi                 2001 non-null   float64
 1   blutus                          2001 non-null   float64
 2   protsessor_tezligi              2001 non-null   float64
 3   ikkita simkartalik              2001 non-null   float64
 4   Oldi_kamera                     2001 non-null   float64
 5   4G                              2001 non-null   float64
 6   Ichki_xotira                    2001 non-null   float64
 7   tel_ingichgaligi                2001 non-null   float64
 8   Rangi                           2001 non-null   float64
 9   Vazni                           2001 non-null   float64
 10  Protsessor yadrolari soni       2001 non-null   float64
 11  Asosiy kamera                   2001 non-null   float64
 12  Qurilma xajmi(pix)              2001 non-null   float64
 13  Qurilma ekran kengligi(pix)     2001 non-null   float64
 14  ram                             2001 non-null   float64
 15  Qurilma xajmi(cm)               2001 non-null   float64
 16  Qurilma ekran kengligi(cm)      2001 non-null   float64
 17  Bir_quvvatlashdagi gaplashish   2001 non-null   float64
 18  3g                              2001 non-null   float64
 19  Qurilma xajmi(pix).1            2001 non-null   float64
 20  sensorli                        2001 non-null   float64
 21  wifi                            2001 non-null   float64
 22  telefon_turi                    2001 non-null   int64
 23  Oldi_kamera_log                 2001 non-null   float64
 24  Rangi_log                       2001 non-null   float64
 25  Qurilma xajmi(pix)_log          2001 non-null   float64
 26  Qurilma ekran kengligi(cm)_log  2001 non-null   float64
 27  Qurilma xajmi(pix).1_log        2001 non-null   float64
dtypes: float64(27), int64(1)
memory usage: 437.8 KB

In [34]:
df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['battereya_hajmi', 'blutus', 'protsessor_tezligi', 'ikkita simkartalik',
       'Oldi_kamera', '4G', 'Ichki_xotira', 'tel_ingichgaligi', 'Rangi',
       'Vazni', 'Protsessor yadrolari soni', 'Asosiy kamera',
       'Qurilma xajmi(pix)', 'Qurilma ekran kengligi(pix)', 'ram',
       'Qurilma xajmi(cm)', 'Qurilma ekran kengligi(cm)',
       'Bir_quvvatlashdagi gaplashish', '3g', 'Qurilma xajmi(pix).1',
       'sensorli', 'wifi', 'telefon_turi', 'Oldi_kamera_log', 'Rangi_log',
       'Qurilma xajmi(pix)_log', 'Qurilma ekran kengligi(cm)_log',
       'Qurilma xajmi(pix).1_log'],
      dtype='object')>

In [37]:
df.skew()

battereya_hajmi                   0.031558
blutus                            0.021006
protsessor_tezligi                0.178815
ikkita simkartalik               -0.039017
Oldi_kamera                       1.020313
4G                               -0.085098
Ichki_xotira                      0.058517
tel_ingichgaligi                  0.087999
Rangi                             1.738971
Vazni                             0.005722
Protsessor yadrolari soni         0.004801
Asosiy kamera                     0.019397
Qurilma xajmi(pix)                0.665905
Qurilma ekran kengligi(pix)       0.016144
ram                               0.007459
Qurilma xajmi(cm)                -0.100813
Qurilma ekran kengligi(cm)        0.633945
Bir_quvvatlashdagi gaplashish     0.010490
3g                               -1.228912
Qurilma xajmi(pix).1              0.665905
sensorli                         -0.013004
wifi                             -0.029010
telefon_turi                      0.000806
Oldi_kamera_log                   0.732324
Rangi_log                        -5.001851
Qurilma xajmi(pix)_log            0.379302
Qurilma ekran kengligi(cm)_log    0.334810
Qurilma xajmi(pix).1_log          0.379302
dtype: float64

# Model Training Process

In [38]:
# separating input and output features,respectively  x and y. 
from sklearn.model_selection import train_test_split

In [40]:
x=df.drop('telefon_turi',axis=1)
y=df['telefon_turi']

In [41]:
# The dataset is divided into two separate parts: a training  and a testing 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# Model Selection

# Random Forest

In [42]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [43]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [44]:
y_pred=rf.predict(x_test)

In [55]:
report_rf=classification_report(y_test,y_pred)

In [56]:
print(report_rf)

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        97
           1       0.95      0.86      0.90       103
           2       0.88      0.92      0.90        90
           3       0.96      0.97      0.97       111

    accuracy                           0.94       401
   macro avg       0.93      0.93      0.93       401
weighted avg       0.94      0.94      0.93       401

# Logistik regression

In [45]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

In [46]:
lg.fit(x_train,y_train)

C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [47]:
y_pred=lg.predict(x_test)

 # Model Evaulation

In [54]:
from sklearn.metrics import classification_report,accuracy_score

In [50]:
report_lg=classification_report(y_test,y_pred)

In [51]:
print(report_lg)

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        97
           1       0.95      0.86      0.90       103
           2       0.88      0.92      0.90        90
           3       0.96      0.97      0.97       111

    accuracy                           0.94       401
   macro avg       0.93      0.93      0.93       401
weighted avg       0.94      0.94      0.93       401

# Comparision Table

In [57]:
from tabulate import tabulate

In [58]:
results=[
['Random Forest with feature transforming',0.94],
['Random Forest without feature transforming',0.89]
]


headers=['Algorithm','Accuracy_score']

table=tabulate(results, headers=headers, tablefmt='grid',floatfmt='.2f')

In [59]:
print(table)

+--------------------------------------------+------------------+
| Algorithm                                  |   Accuracy_score |
+============================================+==================+
| Random Forest with feature transforming    |             0.94 |
+--------------------------------------------+------------------+
| Random Forest without feature transforming |             0.89 |
+--------------------------------------------+------------------+